(function (root) {
  "use strict";

  // v19 프랜차이즈 판정용 기본 사전.
  // 사용자가 검색할 때 외부 API를 호출하지 않으며, GitHub에서 이 파일만 수정해 갱신할 수 있다.
  root.IMM_FRANCHISE_CATALOG = {
    version: "2026-08-25.1",
    updatedAt: "2026-08-25",
    sourceLabel: "임슐랭 주요 브랜드 사전",
    franchises: [
      // 국내 카페·베이커리·디저트
      { brand: "스타벅스", aliases: ["스타벅스", "starbucks"] },
      { brand: "투썸플레이스", aliases: ["투썸플레이스", "투썸", "a twosome place"] },
      { brand: "이디야커피", aliases: ["이디야커피", "이디야", "ediya coffee"] },
      { brand: "메가MGC커피", aliases: ["메가mgc커피", "메가커피", "mega mgc coffee"] },
      { brand: "컴포즈커피", aliases: ["컴포즈커피", "compose coffee"] },
      { brand: "빽다방", aliases: ["빽다방", "paik's coffee", "paiks coffee"] },
      { brand: "더벤티", aliases: ["더벤티", "the venti"] },
      { brand: "커피베이", aliases: ["커피베이", "coffee bay"] },
      { brand: "할리스", aliases: ["할리스", "할리스커피", "hollys"] },
      { brand: "탐앤탐스", aliases: ["탐앤탐스", "tom n toms", "tomntoms"] },
      { brand: "폴바셋", aliases: ["폴바셋", "paul bassett"] },
      { brand: "엔제리너스", aliases: ["엔제리너스", "angel-in-us", "angelinus"] },
      { brand: "카페베네", aliases: ["카페베네", "caffe bene"] },
      { brand: "공차", aliases: ["공차", "gong cha", "gongcha"] },
      { brand: "팔공티", aliases: ["팔공티", "팔공tea", "80tea"] },
      { brand: "아마스빈", aliases: ["아마스빈", "amasvin"] },
      { brand: "쥬씨", aliases: ["쥬씨", "juicy"] },
      { brand: "요거프레소", aliases: ["요거프레소", "yogerpresso"] },
      { brand: "설빙", aliases: ["설빙", "sulbing"] },
      { brand: "배스킨라빈스", aliases: ["배스킨라빈스", "베스킨라빈스", "baskin robbins"] },
      { brand: "던킨", aliases: ["던킨", "던킨도너츠", "dunkin", "dunkin donuts"] },
      { brand: "파리바게뜨", aliases: ["파리바게뜨", "파리바게트", "paris baguette"] },
      { brand: "뚜레쥬르", aliases: ["뚜레쥬르", "tous les jours"] },
      { brand: "명랑핫도그", aliases: ["명랑핫도그", "myungrang hotdog"] },
      { brand: "앤티앤스", aliases: ["앤티앤스", "auntie anne's", "auntie annes"] },
      { brand: "크리스피크림", aliases: ["크리스피크림", "크리스피크림도넛", "krispy kreme"] },

      // 국내 치킨·피자·패스트푸드
      { brand: "교촌치킨", aliases: ["교촌치킨", "교촌", "kyochon"] },
      { brand: "BHC치킨", aliases: ["bhc치킨", "bhc chicken", "bhc"] },
      { brand: "BBQ치킨", aliases: ["bbq치킨", "제너시스bbq", "bbq chicken"] },
      { brand: "굽네치킨", aliases: ["굽네치킨", "굽네", "goobne"] },
      { brand: "네네치킨", aliases: ["네네치킨", "nene chicken"] },
      { brand: "처갓집양념치킨", aliases: ["처갓집양념치킨", "처갓집"] },
      { brand: "페리카나", aliases: ["페리카나", "pelicana"] },
      { brand: "호식이두마리치킨", aliases: ["호식이두마리치킨", "호식이"] },
      { brand: "푸라닭", aliases: ["푸라닭", "puradak"] },
      { brand: "자담치킨", aliases: ["자담치킨", "jadam chicken"] },
      { brand: "노랑통닭", aliases: ["노랑통닭", "norang tongdak"] },
      { brand: "60계치킨", aliases: ["60계치킨", "60 chicken"] },
      { brand: "멕시카나", aliases: ["멕시카나", "mexicana chicken"] },
      { brand: "또래오래", aliases: ["또래오래", "toreore"] },
      { brand: "피자헛", aliases: ["피자헛", "pizza hut"] },
      { brand: "도미노피자", aliases: ["도미노피자", "domino's pizza", "dominos pizza"] },
      { brand: "미스터피자", aliases: ["미스터피자", "mr pizza"] },
      { brand: "피자스쿨", aliases: ["피자스쿨", "pizza school"] },
      { brand: "반올림피자", aliases: ["반올림피자", "반올림피자샵"] },
      { brand: "청년피자", aliases: ["청년피자", "youngman pizza"] },
      { brand: "롯데리아", aliases: ["롯데리아", "lotteria"] },
      { brand: "맘스터치", aliases: ["맘스터치", "mom's touch", "moms touch"] },
      { brand: "KFC", aliases: ["kfc", "케이에프씨"] },
      { brand: "맥도날드", aliases: ["맥도날드", "맥도널드", "mcdonald's", "mcdonalds"] },
      { brand: "버거킹", aliases: ["버거킹", "burger king"] },
      { brand: "써브웨이", aliases: ["써브웨이", "서브웨이", "subway"] },
      { brand: "프랭크버거", aliases: ["프랭크버거", "frank burger"] },
      { brand: "노브랜드버거", aliases: ["노브랜드버거", "no brand burger", "nbb"] },

      // 국내 한식·분식·외식
      { brand: "본죽", aliases: ["본죽", "bonjuk"] },
      { brand: "본죽&비빔밥", aliases: ["본죽&비빔밥", "본죽앤비빔밥"] },
      { brand: "한솥도시락", aliases: ["한솥도시락", "한솥", "hansot"] },
      { brand: "본도시락", aliases: ["본도시락", "bon dosirak"] },
      { brand: "김가네", aliases: ["김가네", "gimgane"] },
      { brand: "바르다김선생", aliases: ["바르다김선생", "김선생"] },
      { brand: "고봉민김밥인", aliases: ["고봉민김밥인", "고봉민김밥", "고봉민"] },
      { brand: "스쿨푸드", aliases: ["스쿨푸드", "school food"] },
      { brand: "죠스떡볶이", aliases: ["죠스떡볶이", "jaws food"] },
      { brand: "아딸", aliases: ["아딸", "addal"] },
      { brand: "두끼", aliases: ["두끼", "dookki"] },
      { brand: "신전떡볶이", aliases: ["신전떡볶이", "sinjeon"] },
      { brand: "청년다방", aliases: ["청년다방", "young dabang"] },
      { brand: "엽기떡볶이", aliases: ["동대문엽기떡볶이", "엽기떡볶이", "엽떡"] },
      { brand: "봉구스밥버거", aliases: ["봉구스밥버거", "봉구스"] },
      { brand: "국수나무", aliases: ["국수나무", "noodle tree"] },
      { brand: "역전우동0410", aliases: ["역전우동0410", "역전우동"] },
      { brand: "새마을식당", aliases: ["새마을식당", "새마을식당0410"] },
      { brand: "홍콩반점0410", aliases: ["홍콩반점0410", "홍콩반점"] },
      { brand: "롤링파스타", aliases: ["롤링파스타", "rolling pasta"] },
      { brand: "미정국수0410", aliases: ["미정국수0410", "미정국수"] },
      { brand: "원할머니보쌈", aliases: ["원할머니보쌈", "원할머니"] },
      { brand: "놀부보쌈", aliases: ["놀부보쌈", "놀부부대찌개", "놀부"] },
      { brand: "박가부대", aliases: ["박가부대", "박가부대찌개"] },
      { brand: "채선당", aliases: ["채선당", "chaesundang"] },
      { brand: "명륜진사갈비", aliases: ["명륜진사갈비", "명륜진사"] },
      { brand: "이차돌", aliases: ["이차돌", "2차돌"] },
      { brand: "하남돼지집", aliases: ["하남돼지집", "hanam pig"] },
      { brand: "팔각도", aliases: ["팔각도", "palgakdo"] },
      { brand: "육회바른연어", aliases: ["육회바른연어", "육바연"] },
      { brand: "생활맥주", aliases: ["생활맥주", "daily beer"] },
      { brand: "역전할머니맥주", aliases: ["역전할머니맥주", "역전할맥"] },
      { brand: "투다리", aliases: ["투다리", "tudari"] },
      { brand: "크라운호프", aliases: ["크라운호프", "crown hof"] },

      // 글로벌·해외 주요 브랜드
      { brand: "Shake Shack", aliases: ["shake shack", "쉐이크쉑", "쉑쉑버거"] },
      { brand: "Five Guys", aliases: ["five guys", "파이브가이즈"] },
      { brand: "In-N-Out Burger", aliases: ["in-n-out burger", "in n out burger", "인앤아웃"] },
      { brand: "Wendy's", aliases: ["wendy's", "wendys", "웬디스"] },
      { brand: "Taco Bell", aliases: ["taco bell", "타코벨"] },
      { brand: "Popeyes", aliases: ["popeyes", "파파이스"] },
      { brand: "Chick-fil-A", aliases: ["chick-fil-a", "chick fil a"] },
      { brand: "Jollibee", aliases: ["jollibee", "졸리비"] },
      { brand: "MOS Burger", aliases: ["mos burger", "모스버거"] },
      { brand: "Freshness Burger", aliases: ["freshness burger", "프레시니스버거"] },
      { brand: "Yoshinoya", aliases: ["yoshinoya", "요시노야", "吉野家"] },
      { brand: "Sukiya", aliases: ["sukiya", "스키야", "すき家"] },
      { brand: "Matsuya", aliases: ["matsuya", "마츠야", "松屋"] },
      { brand: "CoCo Ichibanya", aliases: ["coco ichibanya", "coco壱番屋", "코코이찌방야"] },
      { brand: "Ichiran", aliases: ["ichiran", "이치란", "一蘭"] },
      { brand: "Ippudo", aliases: ["ippudo", "잇푸도", "一風堂"] },
      { brand: "Marugame Seimen", aliases: ["marugame seimen", "마루가메제면", "丸亀製麺"] },
      { brand: "Saizeriya", aliases: ["saizeriya", "사이제리야", "サイゼリヤ"] },
      { brand: "Gyoza no Ohsho", aliases: ["gyoza no ohsho", "교자노오쇼", "餃子の王将"] },
      { brand: "Ootoya", aliases: ["ootoya", "오오토야", "大戸屋"] },
      { brand: "Din Tai Fung", aliases: ["din tai fung", "딘타이펑", "鼎泰豐"] },
      { brand: "Haidilao", aliases: ["haidilao", "하이디라오", "海底捞"] },
      { brand: "Tim Ho Wan", aliases: ["tim ho wan", "팀호완", "添好運"] },
      { brand: "Panda Express", aliases: ["panda express", "판다익스프레스"] },
      { brand: "PizzaExpress", aliases: ["pizzaexpress", "pizza express"] },
      { brand: "Nando's", aliases: ["nando's", "nandos", "난도스"] },
      { brand: "Pret A Manger", aliases: ["pret a manger", "pret", "프레타망제"] },
      { brand: "Costa Coffee", aliases: ["costa coffee", "코스타커피"] },
      { brand: "The Coffee Bean & Tea Leaf", aliases: ["the coffee bean & tea leaf", "coffee bean", "커피빈"] },
      { brand: "Blue Bottle Coffee", aliases: ["blue bottle coffee", "blue bottle", "블루보틀"] },
      { brand: "% Arabica", aliases: ["% arabica", "arabica coffee", "응커피"] },
      { brand: "Luckin Coffee", aliases: ["luckin coffee", "루이싱커피", "瑞幸咖啡"] },
      { brand: "Chatime", aliases: ["chatime", "차타임"] },
      { brand: "Tiger Sugar", aliases: ["tiger sugar", "타이거슈가"] },
      { brand: "The Alley", aliases: ["the alley", "디어앨리"] },
      { brand: "KOI Thé", aliases: ["koi the", "koi thé", "코이티"] },
      { brand: "J.CO Donuts", aliases: ["j.co donuts", "jco donuts", "제이코"] },
      { brand: "Secret Recipe", aliases: ["secret recipe", "시크릿레시피"] },
      { brand: "OldTown White Coffee", aliases: ["oldtown white coffee", "old town white coffee"] },
      { brand: "Texas Chicken", aliases: ["texas chicken", "church's texas chicken"] },
      { brand: "A&W Restaurants", aliases: ["a&w restaurant", "a&w restaurants"] },
    ],
    localChains: [
      { brand: "성심당", aliases: ["성심당", "sungsimdang"], region: "대전 지역 체인" },
      { brand: "이성당", aliases: ["이성당", "leesungdang"], region: "군산 기반 지역 체인" },
      { brand: "옵스", aliases: ["옵스", "ops bakery"], region: "부산 기반 지역 체인" },
      { brand: "런던베이글뮤지엄", aliases: ["런던베이글뮤지엄", "london bagel museum"], region: "복수 지점 브랜드" },
      { brand: "노티드", aliases: ["카페노티드", "노티드", "cafe knotted"], region: "복수 지점 브랜드" },
      { brand: "다운타우너", aliases: ["다운타우너", "downtowner"], region: "복수 지점 브랜드" },
      { brand: "테라로사", aliases: ["테라로사", "terarosa"], region: "강릉 기반 복수 지점 브랜드" },
      { brand: "삼송빵집", aliases: ["삼송빵집", "samsong bakery"], region: "대구 기반 복수 지점 브랜드" },
    ],
  };
})(typeof window !== "undefined" ? window : globalThis);
